### ISSUE TITLE
Second floor size

### ISSUE THREAD

**Issue by laugexd** [owlboy/greatpug-public#10]
**Describe the bug**
The floor on the second floor is not the right size, as can be seen at the stairs besides the entrance to the pug, you can see right through the world.

**To Reproduce**
Just walk up to the second floor and look besides the railing.

**Expected behavior**
It doesn't have any as it doesn't impact colission.

**Screenshots**
![20181130114339_1](https://user-images.githubusercontent.com/20128157/49539941-1f30a300-f8cf-11e8-8f1b-e921116d2389.jpg)

**Are you in VR or Desktop mode?**
VR, but this souldn't affect it.

**Additional context**
Can't think of any.

**Comment by owlboy** [comment]
Thanks for the report, I'll get this fixed.

**Comment by owlboy** [comment]
Fixed!
