### ISSUE TITLE
Burger Bowling

### ISSUE THREAD

**Issue by Ebbeerino** [owlboy/greatpug-public#100]
It sounds goofy because it is. It was an unintended feature of the pug that you could take the hamburger from downstairs all the way up to the roost, and then roll it down the steps around the bend to make it to the landing below. The goal being to get it to the bottom or at least further than everyone else. It has unfortunately been broken for a while as when the burger nears the bottom it will respawn.

Ideally I would be able to play burger bowling again with friends and random players as it was just a goofy way to have some unexpected fun. 

If it doesn't get put back in that's just fine, but it was worth asking about. 

I frequent the pug quite a bit, its my primary place to go run around in and meet new people. I regrettably don't have any screenshots of people playing to give a better understanding of what it is, but it was a solid way to get people to come out of their shell a bit.

**Comment by Ebbeerino** [comment]
If you have any questions about it please let me know, I'm not sure if I explained it well enough. My username in vrc and discord is Ebbee.

**Comment by owlboy** [comment]
This should work better now! Please feel free to reopen or comment with further feedback!

https://github.com/owlboy/greatpug-public/releases/tag/2023.05.19
