### ISSUE TITLE
[VRChat bug?] Fireplace in The Roost being culled by the camera

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#103]
I could have sworn this wasn't a bug until recently.
![VRChat_2023 06 07-20 41](https://github.com/owlboy/greatpug-public/assets/35110496/d21f7225-21a1-490d-a7e8-c56aae9517d1)

**Comment by Wasmachineman-NL** [comment]
Not just the fireplace, also the fish bubbles are culled.

**Comment by owlboy** [comment]
I'm not sure what is preventing these particles from appearing in the camera. They are on the Default layer. I think I'll need some help with this one.

**Comment by Wasmachineman-NL** [comment]
Besides the UI, nope.

**Comment by owlboy** [comment]
@Wasmachineman-NL This was indeed fixed previously, correct? All particles in the world should now use a newer shader.

**Comment by Wasmachineman-NL** [comment]
This is fixed, yes.

**Comment by Wasmachineman-NL** [comment]
I have some bad news:
![VRChat_2023 08 01-22 48_4](https://github.com/owlboy/greatpug-public/assets/35110496/1666ef77-d053-4b68-9c3d-5c8c58e521ef)

**Comment by owlboy** [comment]
I can't reproduce this. Until you have more information beyond a screenshot, I can't do anything.
