### ISSUE TITLE
Basement staircase right side wall has a hole

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#104]
Noticed this when I abused blairx's collider to get into the basement lol
![VRChat_2023-06-08_22-43-50 552_3840x2400](https://github.com/owlboy/greatpug-public/assets/35110496/077acbbf-01c6-49d9-bb76-cf509a5d083a)

**Comment by owlboy** [comment]
This is addressed in the next build. Thanks
