### ISSUE TITLE
Faucets in the bathrooms are missing effects when enabled

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#105]
INVISIBLE WATER
https://www.youtube.com/watch?v=C8ZPTd0jsvI

**Comment by owlboy** [comment]
Thanks, the water should be flowing in the next build. This was some prefab shenanigans causing the issue.

**Comment by Wasmachineman-NL** [comment]
Right side faucet in the men's bathroom still doesn't work, and so does the mop sink in the store room.

**Comment by owlboy** [comment]
Fixed.

**Comment by Wasmachineman-NL** [comment]
Mop sink is still broken.

**Comment by owlboy** [comment]
Ah ha! Ok, that sink should be fixed now. I see how I broke the other ones now too, it was in service of the script this sink uses. But the other sinks don't use the new script yet! This'll be fixed soon.
