### ISSUE TITLE
Very unusual fireplace bug

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#107]
The fireplace in this Pug lobby i'm in just... died out. No fire, nor sound.

It's also not an avatar because I made the screenshot in safe mode.
![VRChat_2023 06 18-21 41](https://github.com/owlboy/greatpug-public/assets/35110496/eeba9115-1b09-45c6-b790-a92add962915)

**Comment by owlboy** [comment]
Did it go out just for you? Or for other people too? 

If you respawned, and re-entered The Roost, did it come back on? It should turn off when you are not in The Roost.

**Comment by Wasmachineman-NL** [comment]
A while later someone else told me the fireplace works for him. Weird. It might actually be related to an avatar I used to quickly jump to the Roost: https://vrchat.com/home/user/usr_43dc9d6a-805d-4823-8328-78a9de3efc04 

This user has a door on their avatar that allows me to quickly jump to the Roost, which might actually explain why the fireplace didn't turn on.

**Comment by owlboy** [comment]
Yes, you currently need to pass through the staircase. I'll consider changing the implementation method. But for now, this is working as intended. Thank you.
