### ISSUE TITLE
Mesh hole near mirror in bar area

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#108]
I certainly hope Bryan isn't going to murder me for how many goddamn issues i'm opening.
![VRChat_2023-06-19_01-30-26 445_3840x2400](https://github.com/owlboy/greatpug-public/assets/35110496/d208af72-37b6-4cbd-9a42-ebd03f87a3fd)

**Comment by owlboy** [comment]
This should be fixed in the next build. Thank you.
