### ISSUE TITLE
Floating objects

### ISSUE THREAD

**Issue by laugexd** [owlboy/greatpug-public#11]
**Describe the bug**
Some objects on the map are floating, i think i've seen a few but the only one i can remember is the couch besides the staircase to the beds up in the roost.

**To Reproduce**
Just look down, possibly change into a smaller avatar.

**Expected behavior**
To not be floating.

**Screenshots**
Not really required.

**Are you in VR or Desktop mode?**
VR, but that doesn't affect this bug.

**Additional context**
None required.

**Comment by owlboy** [comment]
I'll take a look at the couch and get it properly placed. If you run across more, can you comment on this issue listing specifics?

I'll try and keep a closer eye out for things floating off their surfaces. Sometimes it is hard to tell in Unity.

**Comment by owlboy** [comment]
@laugexd Do you mean the fact the couch does not have a bottom to its mesh?

<img width="855" alt="screen shot 2018-12-12 at 7 52 18 pm" src="https://user-images.githubusercontent.com/237349/49910220-74c4fc80-fe47-11e8-826f-66f7c8256bf9.png">

This is intentional.

**Comment by laugexd** [comment]
No the couch should be floating above the floor, in-game it kinda looks like it should have legs by the offset from the ground but it doesn't have any.

**Comment by laugexd** [comment]
![vrchat_1920x1080_2018-12-13_17-31-20 039](https://user-images.githubusercontent.com/20128157/49953040-8ec11680-fefd-11e8-9c15-9e2613b5073c.png)
sorry about the bad lighting but it's the best i could do, anyways that's taken in front of the couch and you can see the back wall, it looks like it is aligned with the wooden thing at the bottom of the wall, but not the floor.

**Comment by owlboy** [comment]
The couch does have legs. I believe you just can't see them due to how dark it appears.

**Comment by owlboy** [comment]
Hmm, it might be LOD actually, thanks for the better shot.

**Comment by owlboy** [comment]
I see the issue now! But I am still investigating what is going on.

**Comment by owlboy** [comment]
This has been fixed. Apologies for the confusion.
