### ISSUE TITLE
Railing is missing collision at the bottom of the back stairs

### ISSUE THREAD

**Issue by owlboy** [owlboy/greatpug-public#111]
![image](https://github.com/owlboy/greatpug-public/assets/237349/e6b8201e-6195-4e81-a763-597dede92112)

> The railing at the bottom of the stairs have no collision
> you can walk through it
> -Froggi

**Comment by Wasmachineman-NL** [comment]
I personally wouldn't mind if this remained unfixed, since it has become part of my Pug routine (spawn, disable music, run upstairs) to run straight through the railing when running to the Roost.

**Comment by owlboy** [comment]
Sorry, I've been meaning to fix this for literally years. – Fixed in the next build.
