### ISSUE TITLE
(Intentional?) Bar seats next to the bar in the center of the world are offset.

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#115]
![VRChat_2023-06-30_17-48-26 191_3840x2400](https://github.com/owlboy/greatpug-public/assets/35110496/8b4b00b4-ac99-4d44-8308-0642defd03b2)
![VRChat_2023-06-30_17-48-50 308_3840x2400](https://github.com/owlboy/greatpug-public/assets/35110496/a6629086-ee6c-4d56-ae0d-10fb29e44a2b)

**Comment by owlboy** [comment]
Tweaked in the next build. Thanks.
