### ISSUE TITLE
Misaligned floor in staircase to Night View Hall

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#116]
OWLBOY please don't murder me for how many goddamn bug reports i'm opening LOL
![VRChat_2023-07-06_17-43-19 506_3840x2400](https://github.com/owlboy/greatpug-public/assets/35110496/c5796e07-f527-4916-b4e7-823984d2e4e1)

**Comment by owlboy** [comment]
Thanks for catching this one. Gaps like this are easy to miss.

 I do appreciate the bug reports and the reports of things like geometry holes.

**Comment by owlboy** [comment]
It was `1.541mm`. Fixed in the next build.

While I was in there, I noticed both the landing and the short run of stairs up to it had older lightmap UVs that I was able to improve too.
