### ISSUE TITLE
Mop sink water sound could be a bit louder

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#117]
It's... very quiet, on my side. Quieter than the sinks in the bathrooms.

**Comment by owlboy** [comment]
Thanks. In the next build all faucets will use the same volume levels/settings.

When assessing if world is at a good volume, please make sure that your volume is set as follows:
* System (Windows) volume: ~70%
* VRChat Master volume: 100%
* VRChat World volume: 70%

Let me know it they all still sound "very" quiet.

**Comment by Wasmachineman-NL** [comment]
Will do so next time I come across something that I consider too quiet, good work as usual Bryan.
