### ISSUE TITLE
Red phone in the bar does not snap back into place

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#120]
Stupid phone was ringing so I ran to it, picked up and when I wanted to place it back, it doesn't snap into place anymore.

**Comment by Wasmachineman-NL** [comment]
Fixed.

**Comment by Wasmachineman-NL** [comment]
Bug has returned.

**Comment by Wasmachineman-NL** [comment]
LOL I tried snapping it back into place, and then this happened:
![VRChat_2023-08-25_17-48-14 913_3840x2400](https://github.com/owlboy/greatpug-public/assets/35110496/fe6cfcff-e579-445c-bfc7-989f9433d0d2)

**Comment by owlboy** [comment]
I think I have the proper solution to this sorted out. The home location kept being mucked with unexpectedly. All things that snap should snap properly moving forward.

https://github.com/owlboy/greatpug-public/releases/tag/2023.08.29
