### ISSUE TITLE
More mesh bugs!

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#127]
![VRChat_2023-08-01_23-05-46 234_3840x2400](https://github.com/owlboy/greatpug-public/assets/35110496/c7caf9db-5127-4df4-b538-e32d251e15c8)
![VRChat_2023-08-01_18-34-48 410_3840x2400](https://github.com/owlboy/greatpug-public/assets/35110496/de966622-0c0d-4dd9-aa8e-f28c82ce03fd)

**Comment by owlboy** [comment]
These are addressed in the next build.
