### ISSUE TITLE
Broken ceiling textures in hallway to back area

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#128]
![VRChat_2023-08-02_23-27-52 120_3840x2400](https://github.com/owlboy/greatpug-public/assets/35110496/d34fe7a1-54fc-4386-8e30-80bee94d7f67)

**Comment by owlboy** [comment]
I'm not sure what caused this, and I can't see it in the editor. But I did confirm it is present for me in VRChat too. We will see if a fresh light bake addresses it in the next build. 🤞

**Comment by Wasmachineman-NL** [comment]
Appears to be fixed now.
