### ISSUE TITLE
beloved rag and medal

### ISSUE THREAD

**Issue by ItsKizzu** [owlboy/greatpug-public#129]
There is a major problem in the pug! Our beloved rag still has yet to make a return. I'm always frustrated whenever i go behind the bar, reaching in that cold empty spot.. and not pulling the rag out.. or the medal from inside the box on the lower shelves behind the bar 

I do have a solution for this! with the upmost respect i request that they make a return to the pug! I for one miss them dearly. I remember wanting to buy vr just to pick that rag up with my own hands. and grab that medal! if it is possible, May we see a return of those wonderful items?  

I've considered, Letting the medal rest easy, but as for the rag, i have no alternatives.

My name in VRC is " Kizzu " and not only would i love to be apart of the pug group, it's like a second home to me, as you can clearly see my picture on the stairway wall that has been there since 2018 I'm totally there, Don't let anyone fool you into thinking i'm not. But i would also appreciate that little slice of 2018 to return to the pug.

**Comment by owlboy** [comment]
These should be back in the latest release! As noted in the patch notes, if I find there are performance issues with the towel, I'll have to remove it again.

Thanks for hanging out at The Pug!

https://github.com/owlboy/greatpug-public/releases/tag/2023.08.24
