### ISSUE TITLE
Bright Lights/Lighting

### ISSUE THREAD

**Issue by auronx223** [owlboy/greatpug-public#13]
**Describe the bug**
Lights and lighting sometimes appears extremely bright, this affects all the lights and the fireplace.  

**To Reproduce**
This appears randomly sometimes the lighting is normal, other times the lights are very bright and have lots of bloom effect. Unsure if the issue also affects avatar lighting.

**Expected behavior**
Lights appear normal, without extreme bloom. 

**Screenshots**
![vrchat_1920x1080_2018-12-18_19-07-37 347](https://user-images.githubusercontent.com/9289155/50190442-25883b80-0321-11e9-9b95-c8fd83bf3c88.png)

![vrchat_1920x1080_2018-12-18_19-19-24 513](https://user-images.githubusercontent.com/9289155/50190451-2d47e000-0321-11e9-83ef-e0cc19458aa0.png)

**Are you in VR or Desktop mode?**
VR with Oculus Rift

**Additional context**

**Comment by owlboy** [comment]
Next time you see this happen, can you please block all shaders and tell me if it goes away?
I suspect this is caused by a shader on someone's avatar as I have never run into it before.

Thanks for the report!

**Comment by jetdog8808** [comment]
a small update to this I joined a pug today and had this popup. wasn't avatars but it did persist into other pug instances even a new public instance I created. a restart to vrchat did fix it but I was unable to reproduce.

**Comment by owlboy** [comment]
Interesting. I have no idea what could be causing this. My bloom is what it has always been. Next time anyone has this happen, please go to other worlds with bloom and see if it carries over there. Since it sounds like a VRChat Bug now since it can travel past unloading the world.

Also, it might still be an avatar if they can trigger the bug.

**Comment by owlboy** [comment]
A new build just went up that uses Post Processing v2. Hopefully this prevents what ever is causing the bloom to flip out.

Please let me know if anyone sees the issue or hears of someone having the issue moving forward!

Thanks again!

**Comment by owlboy** [comment]
The V2 Post Processing stack is in place in The Pug. And settings have been adjusted to hopefully clamp just how bright things can get.

There may still be issues with shader namespace limits that are on-going VRChat wide. But these are issues outside of my control, and VRChat is aware of the issues.
