### ISSUE TITLE
White wine glass wine bug

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#133]
![VRChat_2023-08-25_20-48-20 497_3840x2160](https://github.com/owlboy/greatpug-public/assets/35110496/0354d191-964d-4f5a-837e-d6f8879dd7da)
![VRChat_2023-08-25_20-48-31 168_3840x2160](https://github.com/owlboy/greatpug-public/assets/35110496/3faec4d3-0ead-4355-89df-fa1c2ab085f4)

**Comment by owlboy** [comment]
These should now work roughly like they did in the past. Proper Liquid System support coming later.
