### ISSUE TITLE
Dice Not Landing Flat

### ISSUE THREAD

**Issue by viviaes** [owlboy/greatpug-public#134]
**Describe the Bug** 
throwing dice, they are landing on their side andnnot flattening to the floor.

**Steps To Reproduce** 
Throw dice so it spins during motion

**Expected Behavior** 
Lands flat on the ground after it stops moving

**Screenshots** 
![VRChat_2023-08-25_22-47-36 368_1920x1080](https://github.com/owlboy/greatpug-public/assets/120991050/bfcf638e-f96c-46fe-9b79-6d1d3862e820)

**OutputLog**
[output_log_2023-08-25_22-20-52.txt](https://github.com/owlboy/greatpug-public/files/12443707/output_log_2023-08-25_22-20-52.txt)

**Are you in VR or Desktop mode?**
vr

**Comment by owlboy** [comment]
Dang. This should be fixed now.
