### ISSUE TITLE
Making the red phone stop ringing after X amount of seconds

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#137]
As many Puggers know by now, I idle a ton in The Roost and having to respawn to answer the goddamn phone when no one else is in the lobby gets quite tiring.

How about making it stop ringing after X amount of seconds pass?

**Comment by owlboy** [comment]
I always intended for there to be a timeout. But it appears it was only working for the owner. This should be fixed in the next build.

**Comment by Wasmachineman-NL** [comment]
Seems like this broke again, because it keeps on ringing.

What's even weirder is that it sometimes rings for half a second and then cuts out?
