### ISSUE TITLE
Jumping Toggles Bathroom Mirror - Women's

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#138]
Whenever I jump the mirror culls itself, and it also appears the mirror shrunk a little.
https://i.imgur.com/rMqPkGj.jpg

The men's bathroom mirror also shrunk a little.

**Comment by owlboy** [comment]
Mirror sizes will be consistent in the next build. The jump/trigger issue will have to wait.

**Comment by Wasmachineman-NL** [comment]
The mens bathroom now culls when you stand on the sinks.

**Comment by owlboy** [comment]
> The mens bathroom now culls when you stand on the sinks.

Fixed.
