### ISSUE TITLE
Bloom bugged in Post Processing Stack v2

### ISSUE THREAD

**Issue by HugoZink** [owlboy/greatpug-public#14]
The Great Pug was recently updated to use Post Processing Stack v2. However, the bloom function in PPS v2 seems to be bugged in VRChat, causing weird reflections of your screen on loading avatars and player capsules. Sometimes these textures can align in a way that causes blinding lights, especially in VR.

[Example 1](https://i.imgur.com/iqEA4IU.jpg)

[Example 2](https://i.imgur.com/XaEohdU.jpg)

Unfortunately, the only ways for world creators to fix this seems to be either switching back to v1, disabling the bloom, or waiting for the VRC devs to fix this.

**Comment by KorroBravin** [comment]
This can be mitigated by using the clamping feature for the bloom

**Comment by owlboy** [comment]
I have that turned on, but I guess I need to be much more aggressive.

Also, that does that address the weird broken shaders on selection capsules and the loading avatar. Just the bloom response to them.

**Comment by hackspanner** [comment]
What layers does the PP volume affect? Make sure UI and local players are off.

**Comment by owlboy** [comment]
A comment from Discord about the shaders that are able to make ridiculous bloom amounts:

**Silent** _Today at 12:38 AM_
> Yeah, as far as I can tell, the shader used for player capsule/blue man is bugged somehow
> If it was a NaN error it would be filtered out. I think it's more likely some bad math in the shader, like the highlight is being done using a fresnel calculation but the input isn't normalised or something like that

**Comment by owlboy** [comment]
Bloom is now very clamped/limited.

The shader used for loading avatars and selection capsules needs to be fixed by VRChat.

**Comment by owlboy** [comment]
I’ve received word that this is will likely be fixed in a coming update! This means it won’t be an issue in All worlds.

**Comment by HugoZink** [comment]
This has indeed been fixed in one of the latest VRChat updates, although it was not mentioned in the patch notes.
