### ISSUE TITLE
Mesh holes in kitchen

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#141]
![VRChat_2023-09-09_22-06-12 868_5120x3200](https://github.com/owlboy/greatpug-public/assets/35110496/c20cc65c-8d18-454a-91bb-37e6f4b3d839)

Near the extractor.

**Comment by Wasmachineman-NL** [comment]
Found another hole.
https://i.imgur.com/a7gYxUO.jpg

**Comment by owlboy** [comment]
Fixed in the next build.
