### ISSUE TITLE
Spooky culling bug in The Roost

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#148]
https://i.imgur.com/UPuyfid.jpg
https://i.imgur.com/eaC5Ebu.jpeg

**Comment by Wasmachineman-NL** [comment]
I heard people complain about this yesterday, so still a bug.

**Comment by owlboy** [comment]
This is now fixed. It was actually a post processing volume issue and not occlusion culling. A similar situation near the new window on the stairs is also fixed.
