### ISSUE TITLE
The shelf on the rooster isn't working (can't jump on top of it)

### ISSUE THREAD

**Issue by Ayylmao1911** [owlboy/greatpug-public#151]
**Describe the Bug** 
The shelf on the rooster isn't working (can't jump on top of it)

**Steps To Reproduce** 

**Expected Behavior** 

**Screenshots** 
![shelf](https://github.com/owlboy/greatpug-public/assets/55610412/5672086c-deba-4b1a-8a30-7c845c5bf338)

**OutputLog**

**Are you in VR or Desktop mode?**
Desktop mode

**Additional Context** 

I used to chill in that spot on desktop mode and people would find me up there just chillin in the very right side of the shelf, now I can't chill there. 

https://youtu.be/EcGYihVr_ag (here's a short video showing it) hope you can fix it so I can get back to chilling there<3

**Comment by Ayylmao1911** [comment]
*unless you put it like that and don't want to revent it back to previous state that's respectable. I guess*

**Comment by owlboy** [comment]
I think this is all sorted out now. While I was working on it, it was a bit broken. 🐓
