### ISSUE TITLE
Leaks spotted in the ground ceiling

### ISSUE THREAD

**Issue by kirtide** [owlboy/greatpug-public#154]
Just noticed a hole in the ground ceiling, visible from facing the mirror to the left, above the kitchen-side booths.

![VRChat_2023-10-15_02-24-45 897_3840x2160](https://github.com/owlboy/greatpug-public/assets/10827662/2596a971-03bb-46ac-8a55-cc44453b821f)

Couple more screenshots too and incase it didn't embed properly: https://imgur.com/a/0T3Mv9b

**Comment by owlboy** [comment]
This should be addressed in the next build! Thanks for taking the time to report this!
