### ISSUE TITLE
Toggle for 'Show UI in Mirror' actually disables text

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#155]
Title. Instead of enabling it it disables it.

**Comment by owlboy** [comment]
Thanks!

**Comment by owlboy** [comment]
I tried to reproduce this in editor and failed. Can you test again and provide any more details?

**Comment by Wasmachineman-NL** [comment]
Will rejoin later to check.

**Comment by Wasmachineman-NL** [comment]
Fixed.
