### ISSUE TITLE
Please remove the little ghost on the 2nd floor stage 

### ISSUE THREAD

**Issue by RoamingBarber** [owlboy/greatpug-public#157]
**Is your feature request related to a problem? Please describe.**
Im frustrated with the ghost on the 2nd floor stage for the halloween update as i perform concerts with my friends in fullbody and we have alot of fun but we cant play if theres a little cartoon ghost in the middle of the stage. why add all the cool disco balls and lighting and then put a ghost on the middle of the stage?

**Describe the solution you'd like**
move the little cartoon ghost to the side of the stage away from the middle of the stage 

**Describe alternatives you've considered**
Nothing 

**Additional context**

![image](https://github.com/owlboy/greatpug-public/assets/149249807/6d42c448-01cf-489f-a7ea-ca03de5e7bd8)

**Comment by owlboy** [comment]
Sorry about that. I just pushed an update and the ghosts should be roaming around, or at least not on the stage now.

The Ghosts didn't work out as expected, and from what I saw in multiple instances last night they were all stuck in the wall near the basement door. I never saw one on the stage.

Thanks for taking the time to report this.
