### ISSUE TITLE
Tone down film grain or add toggle

### ISSUE THREAD

**Issue by HugoZink** [owlboy/greatpug-public#16]
Recently, The Great Pug was updated to use Post Processing Stack v2. PPS v2 has fixed a lot of things, one of which is the dithering. Because the dithering was broken in v1, people were recommended to use the "film grain" feature instead.

Now in PPS v2, dithering is not only fixed, it is always on. This should help completely eliminate color banding in darker areas.

I noticed that The Great Pug still uses film grain. While this could be an artistic choice, it becomes _very_ intense on some darker surfaces, to the point where you can even clearly see it in VR. [Here is a picture of a painting in the roost, taken by me.](https://i.imgur.com/mChlZDX.jpg)

[And the grain effect in motion, taken by a friend of mine.](https://gyazo.com/deff9d82d05a7c70ac224704c3927867)

The same effect is also clearly visible on the floor of the bottom floor hallway, although to a lesser extent. It's somewhat disorienting for me in VR when I walk through the hallways or walk up the stairs to the Roost. It also adds a lot of grain to screenshots taken with the ingame camera, which is a shame.

If the film grain is there to prevent color banding, please consider disabling it or decreasing the intensity. If it's there intentionally, please consider adding a toggle somewhere.

**Comment by owlboy** [comment]
I am not using film grain. And I was never using Film Grain or Dither in PP v1. I have been using a shader since August of last year, and have not changed it's setting much since last fall.

It appears that PP v2 forcing dithering is causing me to have double dithering going on. I'll look into it.

**Comment by HugoZink** [comment]
Oh, I see. That makes sense. Thanks for looking into it.

**Comment by owlboy** [comment]
The Pug now only uses the forced Dithering from Post Processing V2
