### ISSUE TITLE
No frame on newly added window

### ISSUE THREAD

**Issue by kirtide** [owlboy/greatpug-public#168]
As described in the title, the newly added window as seen in the preview image on the release page appears to be absent.

![VRChat_2024-02-29_19-27-15 760_3840x2160](https://github.com/owlboy/greatpug-public/assets/10827662/9c44a405-fb9a-4741-8176-483575337aa3)

https://imgur.com/87ObQGR

Initially joined the new version upon instance rejoin, restarting my client shows the issue still persists.

**Comment by owlboy** [comment]
Thank you @kirtide ! This was an occlusion issue. Fixed!
