### ISSUE TITLE
Electric buzzing/AC sound is too loud and can be heard from basically the entire world

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#169]
Which I take offense to because I enjoyed the silence and the crackling of the fireplace in The Roost.

**Comment by Wasmachineman-NL** [comment]
Not just the upper floors, basically the the entire world. Even downstairs behind the Bar I can hear it.

**Comment by owlboy** [comment]
I think these sounds should work as intended now. I'll be able to work on other issues after work tonight.

**Comment by Wasmachineman-NL** [comment]
Great, I'll check later.

**Comment by Wasmachineman-NL** [comment]
Appears to be fixed now.
