### ISSUE TITLE
Can't enter The Great Pug

### ISSUE THREAD

**Issue by ChosenOneVR** [owlboy/greatpug-public#17]
Yesterday, it took me 10 mins to be able to enter the great pug, but today it is more than 10mins. It's been taking forever so I didn't bother to stay anymore. Then, a friend of mine told me that he is also experiencing that problem. A sign that says PLEASE WAIT YOUR PUG IS STILL LOADING.

I even restarted my computer, but it was still the same.

Before, I don't experience this problem.

Here is a screenshot: https://gyazo.com/e850957c3a0c09ad4f5a951fcf731c8b

I was on Desktop Mode.

**Comment by owlboy** [comment]
Please provide your VRChat output log.

Additionally, was this happening in all instances _and_ fresh instances? Or just one?

**Comment by ChosenOneVR** [comment]
It was happening in all instances.

[output_log_11-29-58_PM.txt](https://github.com/owlboy/greatpug-public/files/3124115/output_log_11-29-58_PM.txt)

**Comment by owlboy** [comment]
Thanks for the extra info! I’ll look into this and see if there is anything I can fix on my end or if it’s a VRChat bug.

**Comment by owlboy** [comment]
This appears to be a VRChat bug that is affecting multiple worlds.

**Comment by ChosenOneVR** [comment]
Ohhh I see, I hope vrchat patches this bug. Thanks for letting me know 😁

**Comment by owlboy** [comment]
I believe this issue was resolved in a previous VRChat patch. - Reopen with more details if not!
