### ISSUE TITLE
Bizarre culling bug in women's bathroom stalls

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#173]
![afbeelding](https://github.com/owlboy/greatpug-public/assets/35110496/4cedeafd-581c-41e0-9f6d-b448e40059d4)

**Comment by owlboy** [comment]
Does this still occur? Can you tell if your head (camera) is clipping into any geometry? I wasn't able to reproduce this a few months ago.

**Comment by Wasmachineman-NL** [comment]
Still reproduceable if you clip just right into the stall door.
![afbeelding](https://github.com/owlboy/greatpug-public/assets/35110496/f8dfd100-3321-4cca-b22c-a52af1a8ad39)

**Comment by owlboy** [comment]
Thanks. This is fixed in the next build.
