### ISSUE TITLE
Missing shelf collisions in kitchen storeroom

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#174]
![afbeelding](https://github.com/owlboy/greatpug-public/assets/35110496/94afad39-c6b8-4d35-b75e-0ea3386a40d0)

**Comment by Wasmachineman-NL** [comment]
Kitchen storeroom/refrigerator area shelves also have no collisions.

**Comment by Wasmachineman-NL** [comment]
Walls have been fixed, shelves still are missing collisions.

**Comment by owlboy** [comment]
This will be ready in the next build. Thanks!

I think all of the collision is back to what is intended in here now. I re-applied collision to the shelves in the cooler.
