### ISSUE TITLE
Broken collisions in NVH

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#176]
![afbeelding](https://github.com/owlboy/greatpug-public/assets/35110496/3ab11199-4b7d-4ef7-8652-d222887ad98e)

**Comment by Wasmachineman-NL** [comment]
Actually most of the collisions in the NVH are broken, the ones behind the bar are at least.

**Comment by owlboy** [comment]
I think most of the issues with collision along this side of Night View should be addressed in the next build.
