### ISSUE TITLE
Toning down the brightness in The Roost

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#177]
Especially near the fireplace area. It's too bright and oversaturated for my taste and I wouldn't mind if it was a little more like before the lighting rework.

**Comment by Wasmachineman-NL** [comment]
Not just that, the bloom/color correction also alters the UI of VRChat itself.

**Comment by owlboy** [comment]
The bloom threshold was unintentionally changed. This should fix the UI issue.
Overall brightness and lighting will continue to be iterated on. But for now, things are about how I would like them. Thank you for the feedback.
