### ISSUE TITLE
Glitched lamp texture on chalkboard near entrance

### ISSUE THREAD

**Issue by HugoZink** [owlboy/greatpug-public#18]
A lamp near the entrance (above a chalkboard) has a very weird and glitched texture on it.

Steps to reproduce the behavior: Walk into entrance, turn right immediately, look on the right wall (below the stairs). Above the chalkboard is a tiny lamp, the lamp head has a weird texture on it.

Screenshots: https://imgur.com/a/jGLJlGp

In VR mode, also happens on desktop.

It seems to be a random screenshot of sorts? The texture was not moving.

**Comment by owlboy** [comment]
Thanks for the report! I'll get this fixed soon!

**Comment by owlboy** [comment]
Fixed, thanks for the report!
