### ISSUE TITLE
collision on shed in dumpsters has gone missing

### ISSUE THREAD

**Issue by blair123xyz** [owlboy/greatpug-public#180]
not sure if it's a bug or intended, but hoping it's a bug lol i like sitting up there

also i think the same issue with the bloom/UI is happening in the dumpsters that was happening in the roost in this post: https://github.com/owlboy/greatpug-public/issues/177

**Comment by owlboy** [comment]
Thanks, this will be fixed in the next build later tonight.

**Comment by owlboy** [comment]
A build fixing this went up a few hours ago or so.
