### ISSUE TITLE
too dark of lighting

### ISSUE THREAD

**Issue by POPBIIN** [owlboy/greatpug-public#183]
the lighting is way too dark in the pug. bring the lighting back PLEASEEE

**Comment by owlboy** [comment]
This is something I am still iterating on after switching to a new color profile. The Pug is intended to be a bit dim in many places. But I agree there is still room for improvement.

**Comment by sacred0** [comment]
I enjoy the dimly lit vibe, but perhaps it doesn't look as good on all VR headsets. What about a toggle or slider for brightness in the back room? I understand the lighting is baked, so it can't easily be adjusted at runtime, but some post processing could maybe be good enough.

**Comment by owlboy** [comment]
This is addressed in the next build ☘️. _Sorry for the dim week!_
