### ISSUE TITLE
[D] Udon 2 and World Persistence

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#184]
I wonder how @owlboy thinks about this? Will the Pug get World Persistence like the storeroom toggles being remembered if you leave the instance? Would save me considerable amounts of time every day!

**Comment by owlboy** [comment]
Hello. This would be better placed in the discussion area.

But to answer: 
* As soon as Persistence is available, all toggles will be saved. I've been waiting for this feature for a long time.
* Udon 2 will happen on its own. I don't need to do anything special.

**Comment by Wasmachineman-NL** [comment]
fuck I forgot GitHub actually has such a thing. Either way I can't wait for persistence!
