### ISSUE TITLE
Pool table view in Desktop mode is blocked completely

### ISSUE THREAD

**Issue by MissingNO123** [owlboy/greatpug-public#192]
**Describe the Bug** 
The view of the billiards table in desktop mode is blocked by the light fixture directly above the table, making the game completely unplayable.

**Steps To Reproduce** 
- Launch VRChat in Desktop mode
- Start a game on the billiards table
- Press E
- You cannot see

**Expected Behavior** 
The near clipping plane of the camera attached to the billiards table should be set just above the pool table, or just below the bottom of the light fixture.
Alternatively, the camera can be set to exclude the layer the light fixture is on, if it happens to be on its own layer.

**Screenshots** 
![image](https://github.com/owlboy/greatpug-public/assets/16027333/4259e51d-4aab-40e1-b8c6-ae006048115d)

**OutputLog**

N/A

**Are you in VR or Desktop mode?**
Desktop Mode

**Comment by owlboy** [comment]
This should be fixed now. Thank you.
