### ISSUE TITLE
Balls on the Billiards table act incorrectly

### ISSUE THREAD

**Issue by MissingNO123** [owlboy/greatpug-public#196]
**Describe the Bug** 
The balls appear to get stuck for a few seconds when starting a new game. Additionally, when sinking a ball, it falls straight through the pocket on to the floor and rolls away. 

**Steps To Reproduce** 
- Start a new game
- The balls take a while to spawn
- Sink a ball 
- Some pockets will have no collision (e.g. the top middle pocket)

**Expected Behavior** 
- The animation for the balls spawning should play immediately after starting a game
- The balls should stay in the pocket until they can despawn

**Screenshots** 
Absurdly long startup animation
https://github.com/owlboy/greatpug-public/assets/16027333/64ebe2ef-2b43-47d8-a322-bbb754ed076d

Missing pocket collision
https://github.com/owlboy/greatpug-public/assets/16027333/bba73be6-6410-493d-8c6c-21fd5a9e80f5

**OutputLog**

N/A

**Are you in VR or Desktop mode?**
Desktop, but should be N/A

**Comment by Wasmachineman-NL** [comment]
Have witnessed it firsthand. Not just that, it appears balls aren't synced properly.

**Comment by MissingNO123** [comment]
Sync delay is an inherent problem with VRChat, the VRCBCE table bakes a simulation and then sends that over the network which induces lag but keeps the balls' movements consistent. *Rarely* this breaks, but that's a problem with VRCBCE.

**Comment by owlboy** [comment]
I won't be making modifications to the base functionality of this prefab. Please direct feature requests to [VRCBCE](https://github.com/VRCBilliards/vrcbce/issues). - I plan to update the prefab as updates become available.
