### ISSUE TITLE
Miniscule mesh hole in staircase to NVH

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#197]
https://cdn.discordapp.com/attachments/400330290586714135/1223644850751275099/VRChat_2024-03-30_15-42-41.592_5120x3200.png?ex=661a9b12&is=66082612&hm=b7eaab84221a70ce15e4aecb97cff9d8780453c0456c706a92559b36a6c528ec&

**Comment by owlboy** [comment]
Thanks. This is fixed in the next build.
