### ISSUE TITLE
Buggy station to left of bar

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#198]
![afbeelding](https://github.com/owlboy/greatpug-public/assets/35110496/07897f66-260a-4e74-8395-7463df7b25a8)

**Comment by owlboy** [comment]
I don't see anything different about this station.

**Comment by Wasmachineman-NL** [comment]
Maybe I should have been a little more descriptive: the station in question is very hard to trigger, almost as if it's the infamous raycasting issue.
