### ISSUE TITLE
Misaligned mesh in staircase to loft in The Roost 

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#200]
https://i.postimg.cc/prZ9rcBM/VRChat-2024-04-21-23-48-00-214-5120x3200.png

**Comment by owlboy** [comment]
Thanks. This will be fixed in the next build. And keep an eye out for the new Geometry Holes issue template if you find another hole. It's now an option when you start a new [issue](https://github.com/owlboy/greatpug-public/issues/new/choose).
