### ISSUE TITLE
[Bug] Bathroom sofa on wrong layer.

### ISSUE THREAD

**Issue by Fiszl** [owlboy/greatpug-public#207]
### Describe the Bug

The sofa in the woman's bathroom is on a layer, which I believe to be the local player layer.
It is visible in a mirror, even when the mirror has environment disabled, and is also visible on the camera, but disappears only if the local player layer is disabled.

Without the mirror, or camera, the sofa is invisible to the player.
![20240526084816_1](https://github.com/owlboy/greatpug-public/assets/53832899/7fcc34e1-2571-496f-9c45-b336decb6afb)

### Expected Behavior

I expect the sofa to be visible to the player, and not show up in my mirror or camera with environment disabled.

### Are you in VR or Desktop mode?

VR

### Are you on Linux?

No

**Comment by owlboy** [comment]
Thanks! This will be fixed in the next build.

I was cleaning up incorrect layers in the bathrooms, and this one got misplaced.
