### ISSUE TITLE
[Bug] Pool Cues disappear randomly while holding them in VR

### ISSUE THREAD

**Issue by MissingNO123** [owlboy/greatpug-public#209]
### Describe the Bug

Since the pool cues are marked as static occludees, looking away from their respective spawn points will cause the cues to un-render, even if you're still holding them in your hands. This makes it very hard to play the game in VR. As far as I know, the easiest fix would be either by unmarking them as occludees, or somehow modifying their bounding boxes to cover at least the whole table.

### Expected Behavior

The expected behaviour is that the cues stay rendered and visible while looking away from the pool table.

### Screenshots & Output Logs

Note the spawn point of my cue is on the left side of the table here
https://github.com/owlboy/greatpug-public/assets/16027333/6650d6a2-8639-49b9-b326-fb7bcbf9ebaf

### Are you in VR or Desktop mode?

VR

### Are you on Linux?

No

**Comment by owlboy** [comment]
Thanks for taking the time to report this! - For some reason, this flag was incorrectly set on just the Team 1 pool cue.

This should be fixed now, I did a quick build to address it.
