### ISSUE TITLE
Bathroom Mirror in Great Pug West is Z-Fighting

### ISSUE THREAD

**Issue by ChrisFeline** [owlboy/greatpug-public#21]
Just joined The Great Pug - West today, and entered the bathroom, and saw that the mirror mesh was too close to the wall. Here's a gif: https://gfycat.com/DeepShockedGuppy

**Comment by owlboy** [comment]
Thanks for the report! I’ll get this fixed in the next update.

**Comment by owlboy** [comment]
Fixed.
