### ISSUE TITLE
Door with missing hinges

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#210]
https://i.postimg.cc/Y9L9T4DV/VRChat-2024-05-29-00-03-49-585-5120x3200.png

**Comment by Wasmachineman-NL** [comment]
Just found out the bathroom doors are also missing hinges.

**Comment by owlboy** [comment]
This was intentional in call cases. But I've gone through and updated doors throughout The Pug in the next build.
