### ISSUE TITLE
[Bug] Extremely long power plug in The Roost

### ISSUE THREAD

**Issue by MissingNO123** [owlboy/greatpug-public#213]
### Describe the Bug

This plug would be perfect to plug all of my Long Chargers in to, but unfortunately, I don't have any.

### Expected Behavior

N/A

### Screenshots & Output Logs

![VRChat_2024-06-03_01-48-29 154_2160x3840](https://github.com/owlboy/greatpug-public/assets/16027333/41acd88f-2c1f-4b8d-a037-f7c466c6d1da)
![VRChat_2024-06-03_01-48-50 711_3840x2160](https://github.com/owlboy/greatpug-public/assets/16027333/2227c825-b27e-4c5f-9f0c-0e7dc2bac3dd)

### Are you in VR or Desktop mode?

Desktop

### Are you on Linux?

No

**Comment by owlboy** [comment]
Thanks! Fixed in the next build.
