### ISSUE TITLE
Making the Pug Bug sign clickable

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#214]
Like the 'Join the Pug Group' advertisements!

**Comment by owlboy** [comment]
Only VRChat partners can open URLs in web browsers. Sadly.

**Comment by owlboy** [comment]
I should add: This is for good reason.

**Comment by Wasmachineman-NL** [comment]
Obviously to prevent abuse/IP grabbers. Understandable.
