### ISSUE TITLE
[Bug] Pool table enable button blocked in desktop mode

### ISSUE THREAD

**Issue by MissingNO123** [owlboy/greatpug-public#215]
### Describe the Bug

When in desktop mode, the power button to enable the pool table is blocked by something and can't be clicked unless inside it

### Expected Behavior

Button should be clickable while standing in front of it 

### Screenshots & Output Logs

https://github.com/owlboy/greatpug-public/assets/16027333/c7e6aff0-22a7-4033-9c44-a9baa71600f2

### Are you in VR or Desktop mode?

Desktop

### Are you on Linux?

No

**Comment by owlboy** [comment]
This should be fixed in the next build! Thanks!
