### ISSUE TITLE
Buggy culling on static beer bottles in bar fridge

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#217]
![afbeelding](https://github.com/owlboy/greatpug-public/assets/35110496/7ecc25bf-8354-477a-bb8b-0f9885ce9dc7)

A little hard to get on camera but culling of the bottles acts weird when you move your mouse.

**Comment by Wasmachineman-NL** [comment]
Found another bug: tops of bottles get culled awkwardly.

**Comment by owlboy** [comment]
Addressed in the next build.
