### ISSUE TITLE
The pillars in the Roost are IMO completely unnecessary

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#218]
And no one asked for them either. They block off my line of vision towards the staircase and they feel very, VERY out of place.

**Comment by MissingNO123** [comment]
Going to have to agree on this one. They add visual clutter to that part of The Roost, they serve no functional purpose both in the context of The Great Pug as a building and as a Social VR location, and the colliders physically get in your way trying to walk around that area.

**Comment by OPPEYRADY** [comment]
Yeah it seems a lil much tbh.

**Comment by mossarelli** [comment]
Since the pillars been implemented, there's been a lot less people loitering and hanging where the pillars are located, which I think is a good thing.

**Comment by owlboy** [comment]
After consideration, and letting things breathe for a few months. The posts in The Roost will be staying as they are. I appreciate the feedback.
