### ISSUE TITLE
Overly dark lighting at couch behind staircase to Roost loft

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#221]
A certain monkey that always sits in the center of said couch asked me to open this bug.
https://i.imgur.com/ckQ3uz3.jpeg

**Comment by mossarelli** [comment]
Couch is unevenly lit by the spot lights in the ceiling.

Towards the paintings there's more light, and the opposite there is no light.

**Comment by owlboy** [comment]
> Couch is unevenly lit by the spot lights in the ceiling.
> 
> Towards the paintings there's more light, and the opposite there is no light.

The event lighting is imperfect, and temporary.

The original issue this post was about was already addressed, and the issue should have been closed. If you have further feedback after Halloween is over, feel free to open a new issue. Thanks!
