### ISSUE TITLE
Unusual issue with moving the wine glass

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#225]
A little hard to explain, but the way the wine glass moves is very odd if you hold it and then move to the left or right.

(remind me to record this, I don't have ShadowPlay or OBS installed rn)

**Comment by owlboy** [comment]
I have not been able to identify what might be going on here. Can you please provide more details?

**Comment by Wasmachineman-NL** [comment]
Not a Pug bug, it's to do how VRChat handles props in worlds.
