### ISSUE TITLE
[Bug] Settings panel doesn't open for anyone who isn't the instance master

### ISSUE THREAD

**Issue by MissingNO123** [owlboy/greatpug-public#231]
### Describe the Bug

The settings panel now has a cover over it, but this cover is not able to be interacted with by anyone except the current master of the instance. Once the master clicks to open it, it then opens for *all* players. This implies the state of the panel being open or not is synced globally and controlled by the master rather than being not synced (local) and controlled by the local player. If this is the case then this might also be affecting the persistent variables that are being synced, but I don't have time to set something up to test that yet.

### Expected Behavior

Each player should be able to open the settings panel on their own, and the state of the panel being open should be independent per each player (i.e. local).

### Screenshots & Output Logs

Testing in a world where I'm not instance master, then making a new instance where I am master:
https://github.com/user-attachments/assets/039527c3-19f3-4a9e-a06c-9ec686f907f7

### Are you in VR or Desktop mode?

Desktop

### Are you on Linux?

No

**Comment by owlboy** [comment]
I just pushed an update that should improve this issue.

**Comment by MissingNO123** [comment]
This seems to have fixed the issue 👍

**Comment by MissingNO123** [comment]
Actually - it seems like this bug might affect other interactables in The Pug, I only just now realized the same problem is happening to the faucets that are in the same closet

**Comment by owlboy** [comment]
Please open a new issue if parts of the liquid system are still not working with the newest build uploaded today. Thanks!
