### ISSUE TITLE
The Hunt for Mr. Whiskers Puzzle Can Not Be Completed

### ISSUE THREAD

**Issue by owlboy** [owlboy/greatpug-public#24]
**Describe the bug**
Changes to the client have broken The Hunt for Mr. Whiskers Puzzle in The Great Pug.

I expect to have this fixed in the coming week(s).

**Comment by owlboy** [comment]
This was fixed in the update that occurred on 11/09/18.

**Comment by JewelReeBox** [comment]
I tried The Hunt in The Great Pug and part of the puzzle where the phone is supposed to ring doesn't work.

**Comment by owlboy** [comment]
@JewelReeBox Please make a new issue instead of reopening a 4 year old issue.
