### ISSUE TITLE
LOD Culling is too Aggressive in Some Situations

### ISSUE THREAD

**Issue by ScruffyRules** [owlboy/greatpug-public#25]
**Describe the bug**
Standing in the spawn box has both the down lamps and table poles occluded

**To Reproduce**
Look from spawn to the other side of the room

**Expected behavior**
Down lamps and table poles not disappear

**Screenshots**
Spawn: https://i.scruffyrules.com/hVaYFr.png  
Step over the bar on the floor: https://i.scruffyrules.com/iVUwoZ.png  
Stepping a bit further over https://i.scruffyrules.com/YMmot5.png

**Are you in VR or Desktop mode?**
Desktop

**Comment by owlboy** [comment]
More cases:
<img width="736" alt="Screen Shot 2019-08-28 at 5 10 34 PM" src="https://user-images.githubusercontent.com/237349/63896146-d23db100-c9b6-11e9-82bf-ee68a62b028d.png">
![unknown](https://user-images.githubusercontent.com/237349/63896169-e2ee2700-c9b6-11e9-8cea-f821e382a42a.png)

**Comment by ScruffyRules** [comment]
I completely forgot about the startup settings, I run VRHigh @owlboy.

**Comment by owlboy** [comment]
This incidents listed here should have been improved in the most recent update.

**Comment by owlboy** [comment]
There are new issues with LOD groups in the baseboards on the stairs leading to the roost.

**Comment by owlboy** [comment]
Work continues on adjusting LOD distances. This is mostly addressed/fixed!
