### ISSUE TITLE
Higher quality mirror

### ISSUE THREAD

**Issue by Isaac1475** [owlboy/greatpug-public#28]
You should put a higher quality mirror because it was set to a lower quality mirror for the halloween event and I don't know if it was intentional but it's using the Halloween drinks still.
![Mirror](https://user-images.githubusercontent.com/57301117/68076555-90513280-fd8c-11e9-8f67-35af874be2e4.png)
![drinks](https://user-images.githubusercontent.com/57301117/68076559-a65ef300-fd8c-11e9-8ad4-5050c8c29331.png)

**Comment by owlboy** [comment]
The mirror has been reverted to it's previous (`Auto`) resolution. Also, there is now a toggle in the backroom to reduce the Main Bar mirror resolution down back down to `x1024`.

I'm personally on a GTX 970 and find the `x1024` resolution to be much more gentle on my framerate (VRAM constraints I believe).
