### ISSUE TITLE
Move speakers off stage to ceiling.

### ISSUE THREAD

**Issue by Bradymck** [owlboy/greatpug-public#3]
Possibly add a couple more too. Image for inspiration. 
![vera_project_12](https://user-images.githubusercontent.com/4667076/40135183-e1422bda-5901-11e8-902e-eb7aca6204ea.jpg)

**Comment by Bradymck** [comment]
I like your lights better than these though. lol

**Comment by owlboy** [comment]
These have been moved, and monitors have been added!
