### ISSUE TITLE
Respawning

### ISSUE THREAD

**Issue by st0rmhack3r** [owlboy/greatpug-public#30]
I can load into the game just fine and everyone can see me. But when i try to leave the front door it gives me like 3 second and then teleport's me back I tried to join an new instance but it keeps happening!

**Comment by owlboy** [comment]
@st0rmhack3r, you likely have an avatar on that has colliders on it that are sticking out of the map. This means your avatar is hitting colliders outside of the map that respawn you.

**Comment by st0rmhack3r** [comment]
> @st0rmhack3r, you likely have an avatar on that has colliders on it that are sticking out of the map. This means your avatar is hitting colliders outside of the map that respawn you.

Thanks I thought i was glitching out or something
