### ISSUE TITLE
Front stairs have invisible barrier

### ISSUE THREAD

**Issue by StrixAreForKids** [owlboy/greatpug-public#33]
The front stairs have a strange barrier/collider near the top of the front stairs preventing anyone from going up or down. The only way to get to the top floors is using the back stairs which doesn't have this issue. Someone said it happened during the St. Patrick's Day event but I'm thinking it's the new update that possibly broke it.

**Comment by owlboy** [comment]
@StrixAreForKids does it look like this?

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/237349/78413554-86eb2100-75dd-11ea-8ee9-d898232ab88c.png">

**Comment by StrixAreForKids** [comment]
@owlboy No, like, past the pictures on the wall on the front step, there's an invisible collider preventing you from going up or down.

**Comment by owlboy** [comment]
hah! Sorry totally breezed past your title. I'll get this fixed

**Comment by StrixAreForKids** [comment]
![VRChat_1920x1080_2020-04-03_20-06-36 712](https://user-images.githubusercontent.com/63131124/78415342-c66a3b00-75e6-11ea-8d42-8e38d31209a9.png)
Right here is where the problem is happening.

**Comment by owlboy** [comment]
Thank you!

**Comment by StrixAreForKids** [comment]
Also wanted to let you know the back wall near the mirror, the entire wall have no colliders on them. You can pass right through.

**Comment by owlboy** [comment]
Both issues should be fixed now. Reload the world/switch instance. Lemme know if their is anything else amiss!

**Comment by FroppyRules** [comment]
It is still happening.

**Comment by StrixAreForKids** [comment]
So the wall has been fixed but the stairs still have the collider issue.

**Comment by FroppyRules** [comment]
yes

**Comment by FroppyRules** [comment]
wait no the barrier is still there-

**Comment by FroppyRules** [comment]
the stair barrier

**Comment by FroppyRules** [comment]
Both issues are still there.

**Comment by StrixAreForKids** [comment]
@FroppyRules The back wall got fixed.

**Comment by owlboy** [comment]
Oh but, ok, so I’ve been multi tasking trying to fix this while doing other things. I think I might have it now? But I’m not sure!

**Comment by StrixAreForKids** [comment]
It's been fixed!

**Comment by owlboy** [comment]
Thanks for the report!
