### ISSUE TITLE
Pug West tap triggers have wrong tooltip

### ISSUE THREAD

**Issue by Oofmastre9000** [owlboy/greatpug-public#38]
The taps on The Great Pug West are supposed to say "Pour" when up and "When" ehen they are down, but some of them do not. If I remember correctly all of them say "Pour" when they are up but some of them say "Use" when down, I believe it is the two closest to the door with this issue. This doesnt really affect anything it's just a slightly annoying inconsistency that should be able to be fixed easily enough.

**Comment by owlboy** [comment]
Both states have the same label now! "Use"
