### ISSUE TITLE
The cursed bucket

### ISSUE THREAD

**Issue by Isaac1475** [owlboy/greatpug-public#40]
**Is your feature request related to a problem? Please describe.**
The bucket people use a modified client to put the bucket under you and then pushes you up until your game crashes.

**Describe the solution you'd like**
The same properties that the other object have in the world plates, bottles, etc.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by owlboy** [comment]
This should be fixed. The bucket was on the wrong layer. I reviewed the other pickups and they all appear to be on the correct layer. Let me know if you run into another object with the same issue.

Thanks for taking the time to let me know about this!
