### ISSUE TITLE
Consider Adding Guribo's UdonBetterPlayerAudio

### ISSUE THREAD

**Issue by VenceVR** [owlboy/greatpug-public#44]
**Is your feature request related to a problem? Please describe.**
The Great Pug is quite a popular spot and it usually hits up to 40+ people instances. Players usually end up splitting into groups, but due to VRChat's audio system, everyone's volume is based on distance rather than where you are looking. This can make it somewhat difficult to have conversations in large lobbies when there are several circles nearby. You can also still hear people on the floor below you, but this usually is only an issue when people are talking in the hallway below the stage.

**Describe the solution you'd like**
Consider adding Guribo's "BetterAudio"! A great example of a popular world that currently uses it is The Black Cat and the newer AfterDark Arcade map. The Black Cat uses it subtely, but the Arcade's map is very aggressive. BetterAudio allows several features to change how player audio is transmitted. You can edit it based on direction, whether or not if objects (and players) occlude it, and more. When set up properly, this makes it much easier to focus on your conversation even when several groups are nearby. 
 https://github.com/Guribo/BetterAudio

**Describe alternatives you've considered**
UdonBetterPlayerAudio is one of a kind (I think) in what it does, so there are no alternatives apart from turning down and up players as you are talking to them. This is currently what I do and it can be quite hard to keep track of who you need to turn up and down as people leave and join the conversation. Another alternative is to turn down the audio range, but The Great Pug already has a good balance for this all things considered. It just happens to get hectic in bigger lobbies and when no one is split over the floors.

Thank you for taking the time to read!

**Comment by SalbugVR** [comment]
I would not currently recommend it actually due to a known audio bug that has affected people in both of the worlds you listed that use Guribo’s audio prefab.

https://vrchat.canny.io/bug-reports/p/1128-player-voice-audio-and-world-audio-becomes-2d-and-channels-inverted-under-c

**Comment by owlboy** [comment]
I briefly tested this when it was new. I am very interested in having audio occlusion for player voices. 

I am very paranoid about VRChat bugs causing this to be a _waste of time_. VRChat is slow to fix the sorts of things that are cool but ultimately low priority side components such as VRC Audio Overrides, video players, pickups, and "supported" Unity assets.

I'll try to find time leading up to Halloween at The Pug to test this and see if it causes the audio bug Salbug mentioned. It sure would be awesome to use it for the party.

Thanks for taking the time to make this feature request! I really appreciate it!

**Comment by justiceofrip** [comment]
Hello, I was wondering if there was any update on adding this feature to the great pug? It would make quite the difference!

Thanks

**Comment by owlboy** [comment]
This was added in the latest update! I used v0.8.
