### ISSUE TITLE
VRChat Logfile full of Error "XYZ could not use Station at" when in the world

### ISSUE THREAD

**Issue by farfelu** [owlboy/greatpug-public#47]
**Describe the bug**
Whenever I'm a public The Great Pug instance with many people in it the log file gets blasted with the message 
```
2021.11.15 23:27:25 Error      -  [Behaviour] <SomeUser> could not use Station at :<SomeNumber>/
```
always with different users and numbers.  
30 minutes into the world and the message appears 122492 times.  
```
$ cat output_log_21-13-15.txt | grep "could not use Station at :" | wc -l
122492
```
I asked some people who join me regularly in the instance who also had hundredthousands of those errors in the log.

**To Reproduce**
Join a public "The great pug" instance with many other people and monitor the log file

**Expected behavior**
A less busy log file

**partial OutputLog (usernames redacted)**
```
...
2021.11.15 23:38:47 Error      -  [Behaviour] User01 could not use Station at :18/
2021.11.15 23:38:47 Error      -  [Behaviour] User02 could not use Station at :2D/
2021.11.15 23:38:47 Error      -  [Behaviour] User03 could not use Station at :30/
2021.11.15 23:38:47 Error      -  [Behaviour] User01 could not use Station at :18/
2021.11.15 23:38:47 Error      -  [Behaviour] User02 could not use Station at :2D/
2021.11.15 23:38:47 Error      -  [Behaviour] User03 could not use Station at :30/
2021.11.15 23:38:47 Error      -  [Behaviour] User01 could not use Station at :18/
2021.11.15 23:38:47 Error      -  [Behaviour] User02 could not use Station at :2D/
2021.11.15 23:38:47 Error      -  [Behaviour] User03 could not use Station at :30/
2021.11.15 23:38:47 Error      -  [Behaviour] User01 could not use Station at :18/
2021.11.15 23:38:47 Error      -  [Behaviour] User02 could not use Station at :2D/
2021.11.15 23:38:47 Error      -  [Behaviour] User03 could not use Station at :30/
2021.11.15 23:38:47 Error      -  [Behaviour] User01 could not use Station at :18/
...
```
it's about 56 lines per second.

**Are you in VR or Desktop mode?**
VR on SteamVR

**Additional context**
It doesn't cause any issues, but might be unintended.  
I noticed because I have a log parser running sending me messages through my overlay and it has a visible log output. Whenever I'm in an instance it's just nothing but this error message, I haven't seen any other world do this.

**Comment by owlboy** [comment]
Hello,

Thank you so much for taking the time to report this!

I just pushed an update:
* Removed duplicate Udon Behaviors unexpectedly found on some stations.
* Stations with Udon sync modes set to "none" are now set to "manual" 

I assume the duplicate Udon Behaviors were the cause of the issue. I'm not sure why some of the stations ended up with multiple scripts.

**Comment by owlboy** [comment]
I am not the only one running into this issue:

VRChat Feedback / Canny link:
https://feedback.vrchat.com/bug-reports/p/errorbehavior-xx-could-not-use-station-at-4f

**Comment by owlboy** [comment]
Based on discussing this with others, this is definitely a bug VRChat introduced. Others have reproduced it in their own testing.

Please help support this feedback item:

https://feedback.vrchat.com/bug-reports/p/vrcstation-outputs-error-log-in-1132

**Comment by owlboy** [comment]
Comments posted on the VRChat Feedback Item/Canny in the pervious comment indicate this is likely fixed.
