### ISSUE TITLE
the items are not responding

### ISSUE THREAD

**Issue by Vezzy1** [owlboy/greatpug-public#48]
**Describe the bug**
the items are not respawning in there rightful place 
**To Reproduce**

**Expected behavior**

**Screenshots**

**OutputLog**
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\VRChat\vrchat\` on Windows. There is currently not a simple way to get your log from an Oculus Quest HMD.

You can either attach your log to this issue report. Or link to it from http://pastebin.com

**Are you in VR or Desktop mode?**

**Additional context**

**Comment by owlboy** [comment]
Thanks for the report! I'll look over the pickups soon and make sure they are doing what I expect.

Do you remember which pickups were respawning in the wrong spot? A few days ago I was testing the dice and they seem to work.

**Comment by owlboy** [comment]
I’ve fixed a few items that had incorrect those locations. If this does not fix the item respawn problem you saw, please reopen this issue.
