### ISSUE TITLE
Props are not working

### ISSUE THREAD

**Issue by Vezzy1** [owlboy/greatpug-public#49]
**Describe the bug**
some of the props are not respawning 

**To Reproduce**

**Expected behavior**

**Screenshots**

**OutputLog**
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\VRChat\vrchat\` on Windows. There is currently not a simple way to get your log from an Oculus Quest HMD.

You can either attach your log to this issue report. Or link to it from http://pastebin.com

**Are you in VR or Desktop mode?**

**Additional context**

**Comment by owlboy** [comment]
Please, as I asked on your previous issue. Reopen the issue and provide further details. Which pickups in particular? Do they respawn when you are in a fresh instance alone? Any other details?

https://github.com/owlboy/greatpug-public/issues/48
