### ISSUE TITLE
Visibile seam besides the ground floor staircase at the entrance

### ISSUE THREAD

**Issue by luii** [owlboy/greatpug-public#52]
**Describe the Bug** 
A visibile seam that lets you look into the second floor, you can see it in the top middle of the screenshot

**Steps To Reproduce** 
Stand roughly at the position as i am standing in the Screenshot

**Expected Behavior** 
It shouldnt be possible to look out the seam into the second floor

**Screenshots** 
![VRChat_1920x1080_2022-05-29_08-53-35 023](https://user-images.githubusercontent.com/8077014/170856120-b1c67df0-4a19-48eb-9325-bbd50efb2679.png)

~OutputLog~

**Are you in VR or Desktop mode?**
Desktop and VR Mode (Index)

**Additional Context**

**Comment by owlboy** [comment]
The fix for this is in the next build. Thank you for taking the time to report this issue!
