### ISSUE TITLE
Several issues in The Great Pug West

### ISSUE THREAD

**Issue by Oofmastre9000** [owlboy/greatpug-public#55]
Problem 1:
Some drinks appear to be pitch black.
![VRChat_1920x1080_2022-07-09_03-17-52 431](https://user-images.githubusercontent.com/67082118/178126244-e048d61f-2189-4286-bdf0-7cd75291da68.png)
You can see what they're supposed to look like when you illuminate them with an avatar's flashlight.
![VRChat_1920x1080_2022-07-09_03-18-31 529](https://user-images.githubusercontent.com/67082118/178126255-118b5249-fd2f-4548-a720-885f6d0fd0d2.png)

Problem 2:
The liquid inside of the whiskey bottle appears to be invisible when viewed from above.
![VRChat_1920x1080_2022-07-09_03-19-02 291](https://user-images.githubusercontent.com/67082118/178126300-3eb477af-3e2b-4b48-aeac-d8beae344f1a.png)

Problem 3: 
The floor of the bathroom isn't connected to any of the walls, this lets you see into the void.
![VRChat_1920x1080_2022-07-09_03-19-40 069](https://user-images.githubusercontent.com/67082118/178126324-cc2321ab-fd7c-48ba-bc51-d4ad52aeddef.png)

Problem 4:
The mirror has a large black sphere around it. (The sphere turns green when illuminated with a flashlight.) This black sphere z-fights with the floor.
![VRChat_1920x1080_2022-07-09_03-21-59 642](https://user-images.githubusercontent.com/67082118/178126439-5f9a2c9f-3d67-4c5b-84d8-d46dfdf4e6ae.png)

Problem 5:
The mirror does not deactivate once it's been activated.
![VRChat_1920x1080_2022-07-09_03-23-06 460](https://user-images.githubusercontent.com/67082118/178126446-b2ae6520-8f0e-4349-8bab-810dc5915961.png)

Problem 6:
The seats in some booths are floating above where they should be.
![VRChat_1920x1080_2022-07-09_03-26-10 802](https://user-images.githubusercontent.com/67082118/178126457-fee1c82c-951f-4a16-a6de-6bd02005847f.png)

**Comment by owlboy** [comment]
Everything shown in this issue should be fixed now! Thank you for taking the time to produce a detailed report, it was very helpful.
