### ISSUE TITLE
Re-position spawnpoint for Five Six book.

### ISSUE THREAD

**Issue by Meeran1675** [owlboy/greatpug-public#56]
**Describe the Bug** 
![image](https://user-images.githubusercontent.com/76804021/181858771-beff3b0c-fba5-4cb0-9435-4fb01b97b84a.png)
The Five Six book clips through the shelf, or is positioned incorrectly. The book is on the ground when starting the instance, and re-spawns on the floor near the shelf.

**Steps To Reproduce** 

**Expected Behavior** 
The Five Six book is supposed to stay on top of the bar shelf in Night View Hall upon world initialization, and object re-spawn.

**Screenshots** 

**OutputLog**

**Are you in VR or Desktop mode?**

**Additional Context**

**Comment by owlboy** [comment]
![image](https://user-images.githubusercontent.com/237349/181865003-78c45739-252e-468f-9d12-701be5ceff71.png)

(fixed!)
