### ISSUE TITLE
Sinks are missing object collision and sponge's collider is displaced

### ISSUE THREAD

**Issue by Sarniwoop** [owlboy/greatpug-public#57]
**Describe the Bug** 

The sinks in the mens and womens bathroom has much lower collision than expected, props fall through and lands on a lower collider instead.

The box collider on the sponge prop in the 1st floor bar is at an offset which makes it hover/sink into the environment depending on its orientation.

Screenshots are provided to help show the issues.

![VRChat_1920x1080_2022-07-30_07-14-21 186](https://user-images.githubusercontent.com/61755157/181935257-4d88be70-c5c3-4844-9c41-2b031bb1c299.png)
![VRChat_1920x1080_2022-07-30_07-15-24 937](https://user-images.githubusercontent.com/61755157/181935259-9cc5f43b-bb76-4c95-8079-9afbecada204.png)
![VRChat_1920x1080_2022-07-30_07-16-00 781](https://user-images.githubusercontent.com/61755157/181935262-725e6234-53f9-4762-95a2-76aab8a65100.png)

**Comment by owlboy** [comment]
These should be fixed now.
