### ISSUE TITLE
UI bug - Info panel in Link Generator

### ISSUE THREAD

**Issue by intrepidOlivia** [owlboy/greatpug-public#6]
This isn't directly related to the Pug, but it is related to `thegreatpug.com`, so I hope it belongs here

### **Describe the bug**
In the [VRChat Link Generator](http://thegreatpug.com/vrchat-link-generator/#), sometimes clicking on the Instance Owner help button renders the page unusable by hiding the button necessary to close it.

### **To Reproduce**
Open up Chrome or Firefox.
visit [VRChat Link Generator](http://thegreatpug.com/vrchat-link-generator/#)

**Method 1:**
* click on the `?` icon next to 'Instance Owner' to open the info panel
* click on the `?` icon to close the panel.
* click on the `?` icon one more time
* The icon will now be covered up and the panel will be unable to be closed.

**Method 2:**
* click on the `?` icon next to 'Instance Owner' to open the info panel
* scroll the page with the mouse wheel
* The icon will now be covered up and the panel will be unable to be closed.

**Note**: this bug does not occur with the World ID info panel.

**Comment by owlboy** [comment]
Fixed! 🎉
