### ISSUE TITLE
Excessive Ownership transfer events occur on an object named Bar Sink.

### ISSUE THREAD

**Issue by Superbstingray** [owlboy/greatpug-public#60]
**Describe the Bug** 
There are Excessive Ownership transfer events that occur on an object named Bar Sink. This is likely reducing performance to some extent as it seems to run multiple times per frame increasing its frequency depending on how many players are in the world. This also results in a large output log file size.

**Steps To Reproduce** 
Enter the world with an instance that has players in it and check the output log.

**Expected Behavior** 
Any networked object should not transfer ownership that many times per second/frame.

**Screenshots** 

https://user-images.githubusercontent.com/74171114/184476834-ad70302c-94d3-4309-a3c6-d8af647ff221.mp4

**OutputLog**
View attached video.

**Are you in VR or Desktop mode?**
Both.

**Additional Context**

**Comment by owlboy** [comment]
Thank you, I'll get this sorted out today.

**Comment by owlboy** [comment]
This should be fixed now. Thank you for the detailed report! 😃

The bar sink scripts have been totally rewritten to use events, and the faucets should be more responsive now.

**Comment by owlboy** [comment]
This should be fixed now. Thank you for the detailed report! 😃

The bar sink scripts have been totally rewritten to use events, and the faucet handles should be more responsive now.
