### ISSUE TITLE
The carpet in The Roost appears in the camera and personal mirror in some modes

### ISSUE THREAD

**Issue by o0F-0oF** [owlboy/greatpug-public#62]
**Describe the Bug** When you open up the camera, put it on green screen it shows the carpet in the roost

**Screenshots** 
![image](https://user-images.githubusercontent.com/76185649/187816427-5b42bf81-0b75-49e6-87b1-2d66ba82aa43.png)

**Are you in VR or Desktop mode?**
Desktop

**Comment by o0F-0oF** [comment]
It appears that this only happens when you have both remote player and green screen on the will rug pop up

**Comment by blair123xyz** [comment]
same issue with the personal mirror, when you have remote players set to be shown in the mirror it shows the carpet

**Comment by owlboy** [comment]
The issue causing the carpet to unexpectedly appear in cameras and personal mirrors should be fixed now.
