### ISSUE TITLE
Music toggle in store room control panel?

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#64]
Title. As much the music is great I prefer not listening to it for hours on end.

**Comment by owlboy** [comment]
Added! Thank you for taking to time to make an issue!

**Comment by Wasmachineman-NL** [comment]
It appears the switch is broken, the music stops for a second and starts playing again when I use the music toggle in the storeroom.

**Comment by owlboy** [comment]
I'll try to take a look at this later today. It appeared to be working properly. 

Thanks for following up!

**Comment by owlboy** [comment]
I've overhauled and improved the switch this toggle is using. It appears to be working correctly at the moment. Can you confirm @Wasmachineman-NL ? Rejoining will update the world.

**Comment by Wasmachineman-NL** [comment]
Can confirm it still not working correctly, the switches move much slower now though!

**Comment by Wasmachineman-NL** [comment]
Whoops, never bothered updating this issue. It's working now, thanks.
