### ISSUE TITLE
Rogue mesh?

### ISSUE THREAD

**Issue by HachijoTohya** [owlboy/greatpug-public#65]
**Describe the Bug**

There seems to be a rogue box mesh around the women's bathroom in the pug

**Steps To Reproduce**

Go to the pug bathrooms to see it

**Expected Behavior** 

**Screenshots** 

https://i.imgur.com/hGoddUK.jpeg

**OutputLog**

N/A

**Are you in VR or Desktop mode?**
VR

**Additional Context** 
N/A

**Comment by KadachiiVR** [comment]
Confirming that I'm also getting this.

**Comment by ShiguriVR** [comment]
Confirming the confirmation.

**Comment by owlboy** [comment]
Thanks for the quick report on this! I'll be fixing this shorty.

**Comment by owlboy** [comment]
Fixed!
