### ISSUE TITLE
Women's bathroom mirror culls and turns off before it should.

### ISSUE THREAD

**Issue by ShiguriVR** [owlboy/greatpug-public#66]
**Describe the Bug** Seems like there's an issue with the occlusion and/or trigger volume for the mirror in the women's bathroom.

**Steps To Reproduce** Back away from the mirror until you reach the back wall. First you will be culled out of the mirror, then if you step all the way back it turns off.

**Expected Behavior** Mirror should work as expected until you actually leave the room.

**Screenshots** See video attached.

**OutputLog** I will post this if it's actually required but this doesn't seem like the type of issue where it'd be helpful.

**Are you in VR or Desktop mode?** Can be reproduced in both.

https://user-images.githubusercontent.com/85214506/205929388-0bfc9e6b-2c42-4347-be18-fc0f3429076d.mp4

**Comment by owlboy** [comment]
Updated! Adjusted culling and toggle collider.

**Comment by owlboy** [comment]
Updated.
