### ISSUE TITLE
Bad Culling Spot

### ISSUE THREAD

**Issue by ShiguriVR** [owlboy/greatpug-public#67]
**Describe the Bug** Another culling issue that can be found from one of the seats towards the back of the Pug.

**Steps To Reproduce** See attached video.

**Expected Behavior** Culling shouldn't occur there.

**Screenshots** See attached video.

**OutputLog** Irrelevant.

**Are you in VR or Desktop mode?** Reproducible in both.

https://user-images.githubusercontent.com/85214506/206443028-4aade9ba-5c5d-473a-89ef-ffabe950e15b.mp4

**Comment by owlboy** [comment]
Your camera was inside the mesh. I've adjusted things. 

Changes will be in the next build. Thank you.
