### ISSUE TITLE
Specular Aliasing (?) Throughout the Pug when MSAA is Enabled

### ISSUE THREAD

**Issue by ShiguriVR** [owlboy/greatpug-public#69]
**Describe the Bug** Do you remember the bug I reported a while back of the display case for the katana in the Roost having a shimmering effect? Yeah, turns out that's going on with most of the objects in the pug when MSAA is enabled, just to a lesser degree, especially on transparent objects (but also on the edges of some opaque objects, especially at a distance). Moving your viewpoint around transparent objects causes a bit of a lightshow. 

Like the aforementioned glass case it started happening when you changed shaders and so I assume it's possibly the same issue. From what experience I have with things I think this is specular aliasing (and I figure the fix would be in shader via either adjusting specular settings or having specular anti-aliasing).

**Steps To Reproduce** See videos.

**Expected Behavior** No or less light shimmering. I mean sure, it would be realistic, especially for glass, to have some shimmering effect near edges or where light is being strongly bent, but only when exposed to bright light and not like this.

**Screenshots** See videos.

I used the glasses behind the bar on the first floor, probably where it's the most pronounced now.
The first video shows them with MSAA disabled and the issue doesn't exist, wheras the second is with MSAA x8.
Oddly enough I think the issue is actually a bit more muted than it was at one point, but maybe that's just my imagination? 🤔 

**OutputLog** Irrelevant.

**Are you in VR or Desktop mode?** Reproducible in both, more noticeable in VR.

**Additional Context** On a personal note I usually run VRChat with 4x MSAA because I've been taught that it's the sweet spot before diminishing returns really kicks-in performance wise.

Oh, and, sorry for all the bug reports all of a sudden. I had a few bugs that I was keeping to myself and figured someone else would eventually report, but now I'm just dropping them all at once because I've suddenly had some energy for it. Keep in mind that I'm far more nit-picky with the Pug because I care about the place and I get really detail-oriented about the things I care about, I'm not meaning to be whiny or something. Thanks for keeping it in good shape👍

https://user-images.githubusercontent.com/85214506/206456972-fcc460d3-bc8a-4a66-86f5-54af99686c27.mp4

https://user-images.githubusercontent.com/85214506/206457002-675f403a-96cf-457c-beae-db10c033ef87.mp4

**Comment by owlboy** [comment]
Yes, it's more muted than before. I adjusted it last time you brought it up when I also made other changes to address the large prominent artifacts. This is the best I can do right now, and otherwise I prefer the overall appearance this shader gives.

This is an [issue](https://gitlab.com/s-ilent/fake-glass/-/issues/2) with silent's Fake Glass shader. And this shader does not yet have the anti-aliasing feature other shaders have.

Thank you.
