### ISSUE TITLE
The Great Pug | Mirrors Rendering is a bit weird in recent updates |

### ISSUE THREAD

**Issue by skppiy4000** [owlboy/greatpug-public#70]
**Describe the Bug** 
Seems in the recent updates, mirrors have stopped rendering the moon.

**Steps To Reproduce** 
Stand infront of mirror, place object down or look at moon, it doesn't render, sometimes it even flickers objects.

**Expected Behavior** 
Moon rendering correctly.

**Screenshots** ![image](https://user-images.githubusercontent.com/78286476/208278962-0146c48f-5056-4dd8-aaa5-1b4b95093167.png)
![image](https://user-images.githubusercontent.com/78286476/208278971-87045855-47ab-49e0-b22c-46b93929f87a.png)

**Are you in VR or Desktop mode?**
Desktop

**Additional Context** 
This also has a byproduct of not rendering objects that are "world constraints" like items on avatars, tested it using older
varients of my own models and rendering ceased, it worked in prior updates to the pug, is this intentional, it's extremely annoying when hanging out with friends. (It seems to also cause some weird seizure inducing flickering at times depending on the avatars used).

**Comment by owlboy** [comment]
Thanks for the report. I'll be looking at this shortly. I think I know what's causing this.

**Comment by owlboy** [comment]
Adjustments were made on 12/21/22. @skppiy4000 do you still experience issues with avatars?

**Comment by skppiy4000** [comment]
Yes, I do still experience it with avatars, the moon is back however. https://vrlabs.dev/item/world-constraint is a example of stuff that does not tone well and stops rendering, which can cause visual oddities.

**Comment by owlboy** [comment]
@skppiy4000 Following up again.

Does this issue still occur with avatars after todays update?
I just updated to version 1.22 of [DistanceCullingMirrors](https://github.com/Superbstingray/DistanceCullingMirrors).

cc @Superbstingray

**Comment by Superbstingray** [comment]
It makes sense that the moon wasn't rendering originally as it would have been out of range of the distance culling, however the constrained objects/meshes not showing correctly in mirrors as far as I know is due to how VRChat handles mirror reflections with the MirrorReflection and PlayerLocal layers behaving differently. If the difference is being caused by my DistanceCullingMirrors script having more details or confirmation that it only occurs in mirrors using the script would be helpful.

**Comment by skppiy4000** [comment]
> 

Just saw this, seems to be fixed! it is now correctly rendering again, and avatars are also now properly rendering with world constraints as well.

**Comment by owlboy** [comment]
@skppiy4000 Thanks for getting back to me! I'm glad things are working now!

@Superbstingray Looks like things are good! In this case I set the distance on `Other Culling Distances` to a high number to make sure it reached to origin.
