### ISSUE TITLE
Great Pug rose loses collision when it is picked up

### ISSUE THREAD

**Issue by HachijoTohya** [owlboy/greatpug-public#71]
**Describe the Bug** 
When the rose is activated and then picked up and dropped, it loses all collision and falls through the world perpetually. 

**Steps To Reproduce** 
Activate the rose, pick it up, and drop it

**Expected Behavior** 
The rose should stop falling when it hits the floor.

**Screenshots** 
https://user-images.githubusercontent.com/57164082/209769083-d196430b-265f-44ca-84ac-a92a26dd88bf.mp4

**OutputLog**

[output_log_2022-12-28_00-08-24.txt](https://github.com/owlboy/greatpug-public/files/10312564/output_log_2022-12-28_00-08-24.txt)

**Are you in VR or Desktop mode?**
VR

**Additional Context** 
N/A

**Comment by owlboy** [comment]
This should be fixed I the next build! Thank you!
