### ISSUE TITLE
Misplaced collision in the Roost

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#74]
The pillar near the staircase to the beds in the Roost has a too large collision box:
![VRChat_2023-01-01_23-29-22 415_3840x2400](https://user-images.githubusercontent.com/35110496/210186393-e1f3c464-af38-4d37-a89f-ee048c5b3909.png)

Strange thing is, I can stand just fine in the left corner, but in the right one I get stopped halfway.

**Comment by owlboy** [comment]
Fixed in the next build.

Thanks for letting me know about this!
