### ISSUE TITLE
Culling bug on the entrance noticeboard

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#76]
![VRChat_2023-01-02_13-47-19 688_3840x2160](https://user-images.githubusercontent.com/35110496/210233363-bb56a0ce-a6f6-47fc-8e96-bdc082dffba5.png)
![VRChat_2023-01-02_13-47-22 779_3840x2160](https://user-images.githubusercontent.com/35110496/210233369-df87b656-4ba4-4703-8abf-447e45449e42.png)

**Comment by owlboy** [comment]
Generally, the items on this board are culled aggressively after you leave the entrance area. But I have adjusted things a bit more.
