### ISSUE TITLE
Geometry showing through the staircase near store room/dumpster area

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#77]
![VRChat_2023 01 22-13 44](https://user-images.githubusercontent.com/35110496/213916504-4b4af8db-2e32-4d79-b83e-275869ede836.png)

Very minor but noticable.

**Comment by owlboy** [comment]
If you are pointing out those white pixels in your screenshot, then these are not geometry issues. These are rendering issues with rendering glancing angles and I'm not sure how to fix them.
