### ISSUE TITLE
Ability to see chatbox in pug mirror

### ISSUE THREAD

**Issue by blair123xyz** [owlboy/greatpug-public#78]
**Is your feature request related to a problem? Please describe.**
Can't see chatbox in pug mirrors

**Describe the solution you'd like**
Seeing when users are typing in the chatbox while looking at the mirror

**Describe alternatives you've considered**
Currently you either have to have notification sounds enabled (and hope you hear it lol) and turn around and/or use the personal mirror on top of the pug mirror (which doesn't work great because of the angle of the mirror)

Screenshot shows how the chatbox appears in personal mirror but not in pug mirror

![VRChat_2023-01-30_20-14-15 336_1920x1080](https://user-images.githubusercontent.com/112629268/215633907-490924a9-6640-4a17-bb55-3a325429e069.png)

**Comment by owlboy** [comment]
A UI toggle has been added to the panel in the back room for the main mirror.

Thank you for bringing this to my attention.

![2-1-2023 4_35_44 PM](https://user-images.githubusercontent.com/237349/216204381-ada7e9bd-167c-439d-a18a-d2510c18ee36.png)

**Comment by blair123xyz** [comment]
Thank you for adding this so soon! Unfortunately, it seems the mirror is off by default now until you click the button 😅 

![VRChat_2023-02-02_00-48-43 312_1920x1080](https://user-images.githubusercontent.com/112629268/216242715-491e50ea-d175-42ae-bd66-e7a9207f76f6.png)

**Comment by owlboy** [comment]
I think this should be fixed now. Thanks for following up!

**Comment by Wasmachineman-NL** [comment]
Can this be extended to also the bathroom mirrors?
