### ISSUE TITLE
Seat toggles no longer function

### ISSUE THREAD

**Issue by Cobalt60VRC** [owlboy/greatpug-public#79]
**Describe the Bug** 

the seat toggle buttons no longer toggle the seats
**Steps To Reproduce** 
click the seat toggle buttons

**Expected Behavior** 
seat toggle buttons toggling the seats

**Screenshots** 

**OutputLog**

**Are you in VR or Desktop mode?**
vr

**Additional Context** 
broke in the latest update

**Comment by owlboy** [comment]
Thanks for the report! I'll address this later tonight.

**Comment by owlboy** [comment]
This should be fixed! Thanks again!
