### ISSUE TITLE
Very weird prop behavior near greeter desk

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#84]
I was talking to AI Joken and I just noticed this very weird bug regarding props, they break physics/float in mid-air:
![steamappid438100_2023 03 10-12 27](https://user-images.githubusercontent.com/35110496/224304611-81a59f1a-474f-47b2-8cae-c3a70084f9e0.png)

**Comment by Wasmachineman-NL** [comment]
lol not just at Joken's desk, even at the Bar it happens
![VRChat_2023 03 10-16 04](https://user-images.githubusercontent.com/35110496/224350327-4ca8cb90-a066-4bc4-8236-082ef9110d05.png)

**Comment by owlboy** [comment]
This should be addressed now. But what's so bad about floating pickups? Everyone else seems to love them…

**Comment by Wasmachineman-NL** [comment]
Still a issue.
![VRChat_2023 03 11-21 04](https://user-images.githubusercontent.com/35110496/224509332-1a158ec4-e9fb-425a-8b26-fb5197d9a718.png)

**Comment by owlboy** [comment]
Further adjustments have been made.

**Comment by Wasmachineman-NL** [comment]
The bug has returned.
![VRChat_2023 08 18-22 30](https://github.com/owlboy/greatpug-public/assets/35110496/1b5d2a40-c05e-4ba9-8d78-d37fa81d2662)
