### ISSUE TITLE
Broken collisions on bathroom doors

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#86]
I'm getting real Deus Ex flashbacks from this lol
![VRChat_2023-03-11_22-01-33 469_3840x2400](https://user-images.githubusercontent.com/35110496/224511457-081fd717-9bf2-4efb-b4a7-feca724a9e79.png)
![VRChat_2023-03-11_22-03-04 645_3840x2400](https://user-images.githubusercontent.com/35110496/224511509-be568d97-e244-4bc7-b764-77eb8a5c4764.png)

**Comment by owlboy** [comment]
Thanks, some adjustments to the hierarchy bumped these out of position.
They should be fixed now.
