### ISSUE TITLE
Leprechaun puzzle impossible to complete on desktop

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#88]
Either the one in the men's bathroom in the right stall or the picture by the dumpster are not pickupable in desktop.

**Comment by owlboy** [comment]
I hope things work better next event. Closing for now.

Please spread the word about this item on the VRChat Feedback Boards:
https://feedback.vrchat.com/bug-reports/p/make-desktop-user-pickup-ray-casting-work-in-situations-where-it-works-for-vr-us-1
