### ISSUE TITLE
Weird skybox gradient near dumpsters

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#89]
Not sure if intentional or not.
![VRChat_2023-03-24_21-33-21 001_3840x2400](https://user-images.githubusercontent.com/35110496/227635093-6e9f5724-9289-48aa-8df5-2ee61e540672.png)

**Comment by owlboy** [comment]
Fixed.

**Comment by Wasmachineman-NL** [comment]
It appears the gradient is back?
![Uploading VRChat_2023-05-15_12-22-35.282_3840x2400.png…]()

**Comment by owlboy** [comment]
It's intentional. It's been there for years. What you initially noticed was a broken version of it.

This is the intended appearance of the top of The Pug from the ground.

Thank you.
