### ISSUE TITLE
Props being culled by mirrors (intentional?)

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#92]
Is this intentional?
![VRChat_2023-04-02_20-58-42 626_3840x2400](https://user-images.githubusercontent.com/35110496/229373216-731cc25a-0fb4-4e4c-9912-bcb1dc8c8219.png)

**Comment by Wasmachineman-NL** [comment]
Interestingly enough, the iPod doesn't get culled:
![VRChat_2023 04 07-12 23](https://user-images.githubusercontent.com/35110496/230592752-1317da30-941f-47f3-a91b-c796b53a5c59.png)

**Comment by owlboy** [comment]
I've extended the pickup culling distance on the mirrors. This may have addressed the issue.

**Comment by Wasmachineman-NL** [comment]
While it did, it still is culling fluids in glasses. Probably unfixable.r
![VRChat_2023 05 06-13 22](https://user-images.githubusercontent.com/35110496/236621107-7ba0f440-b80a-4fd3-86fd-9ec193e6075e.png)

**Comment by Wasmachineman-NL** [comment]
That, and the whiskey bottle still gets culled.

**Comment by owlboy** [comment]
I've made some adjustments that might improve this. I think the Whiskey bottle should show up properly now. These changes will be in the next build.

**Comment by owlboy** [comment]
Pickups and other props should be working as expected. Please open a new issue if something _changes_.
