### ISSUE TITLE
Stairs up from nightview to roost first platform to continuing up the stairs can kick user back towards the platform

### ISSUE THREAD

**Issue by lexvi** [owlboy/greatpug-public#97]
Stairs up from nightview to roost first platform to continuing up the stairs can kick user back towards the platform

**Steps To Reproduce** walk up the staits, get stuck

**Expected Behavior** not get stuck

**Are you in VR or Desktop mode?** VR

**Additional Context** Clearly caused by the funny new bouncy platforms

**Comment by owlboy** [comment]
I think this should be fixed now. Please reopen/comment if any section of the stairs is still causing this.
