### ISSUE TITLE
Amorphous blob loitering menacingly above dumpster

### ISSUE THREAD

**Issue by halomademeapc** [owlboy/greatpug-public#98]
Describe the bug
There is a dark, low-polygon blob floating above one of the dumpsters in the back alley.  I do not like this blob.  Its smug aura mocks me.

To Reproduce
Go to the back alley and look above the rightmost dumpster

Expected behavior
There should be fresh, pure, blobless dumpster air in this region.

Are you in VR or Desktop mode?
VR

![VRChat_2023-05-14_23-24-08 254_7680x4320](https://github.com/owlboy/greatpug-public/assets/5904472/d0b095fb-d00f-4714-9582-a28a873eb9a0)

**Comment by owlboy** [comment]
Thanks for the report. The blob will be vanquished in the next build!

**Comment by halomademeapc** [comment]
Magnificent, thank you
